name: Release

on:
  pull_request:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 'lts'
    - name: Install, Build, Publish
      run: |
        npm ci
        npm run build
        ls -la dist
        npx semantic-release
